spring:
  application:
    name: springsecuritysection4
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

    jpa:
      show-sql: ${JPA_SHOW_SQL:true}
      properties:
        hibernate:
          format_sql: ${HIBERNATE_FORMAT_SQL:true}

